# Documentation: https://roots.io/trellis/docs/ssh-keys/
admin_user: admin

# Also define 'vault_users' (`group_vars/staging/vault.yml`, `group_vars/production/vault.yml`)
users:
  - name: "{{ web_user }}"
    groups:
      - "{{ web_group }}"
    keys:
      - https://github.com/emhoracek.keys
      - https://github.com/dhartunian.keys
      - https://github.com/mattraibert.keys
      - https://github.com/cassiemoy.keys
      - https://github.com/misfist.keys
  - name: "{{ admin_user }}"
    groups:
      - sudo
    keys:
      - https://github.com/emhoracek.keys
      - https://github.com/dhartunian.keys
      - https://github.com/mattraibert.keys
      - https://github.com/cassiemoy.keys
      - https://github.com/misfist.keys
  - name: misfist
    groups:
      - sudo
    keys:
      - https://github.com/misfist.keys

admin_user: ubuntu
web_user: web
web_group: www-data
web_sudoers:
  - "/usr/sbin/service php7.0-fpm *"
