---
- name: Require manual definition of remote-user
  fail:
    msg: |
      When using `--ask-pass` option, use `-u` option to define remote-user:
      ansible-playbook server.yml -e env={{ env | default('production') }} -u root --ask-pass
  when: ansible_user is not defined and cli_ask_pass | default(false)

- name: Set remote user for each host
  set_fact:
    ansible_user: "{{ admin_user }}"
  when: ansible_user is not defined

- name: Announce which user was selected
  debug:
    msg: "Note: Ansible will attempt connections as user = {{ ansible_user }}"

- name: Load become password
  set_fact:
    ansible_become_pass: "{% for user in vault_users | default([]) if user.name == ansible_user and user.password is defined %}{% if loop.first %}{{ user.password }}{% endif %}{% endfor %}"
  when: ansible_user != 'root' and not cli_ask_become_pass | default(false) and ansible_become_pass is not defined
  no_log: true
